# Generated by Django 4.0.3 on 2022-04-09 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'required': 'Por favor, insira o nome do Pokémon.'}, help_text='Ex: Blaziken', max_length=100, verbose_name='Nome do Pokémon')),
                ('numero_pokedex', models.CharField(help_text='Ex: 001', max_length=3, validators=[django.core.validators.RegexValidator('^\\d\\d\\d$', message='Insira um número válido.')], verbose_name='Número da Pokédex')),
                ('tipo_1', models.CharField(choices=[('normal', 'Normal'), ('fogo', 'Fogo'), ('agua', 'Água'), ('grama', 'Grama'), ('voador', 'Voador'), ('lutador', 'Lutador'), ('veneno', 'Veneno'), ('eletrico', 'Elétrico'), ('terra', 'Terra'), ('pedra', 'Pedra'), ('psiquico', 'Psíquico'), ('gelo', 'Gelo'), ('inseto', 'Inseto'), ('fantasma', 'Fantasma'), ('ferro', 'Ferro'), ('dragao', 'Dragão'), ('sombrio', 'Sombrio'), ('fada', 'Fada')], error_messages={'required': 'É necessário escolher o primeiro tipo.'}, help_text='Escolha um tipo para o pokémon', max_length=50, verbose_name='Primeiro tipo')),
                ('tipo_2', models.CharField(blank=True, choices=[('normal', 'Normal'), ('fogo', 'Fogo'), ('agua', 'Água'), ('grama', 'Grama'), ('voador', 'Voador'), ('lutador', 'Lutador'), ('veneno', 'Veneno'), ('eletrico', 'Elétrico'), ('terra', 'Terra'), ('pedra', 'Pedra'), ('psiquico', 'Psíquico'), ('gelo', 'Gelo'), ('inseto', 'Inseto'), ('fantasma', 'Fantasma'), ('ferro', 'Ferro'), ('dragao', 'Dragão'), ('sombrio', 'Sombrio'), ('fada', 'Fada')], help_text='Escolha o segundo tipo para o pokémon, se necessário', max_length=50, null=True, verbose_name='Segundo tipo')),
                ('hp', models.IntegerField(help_text='87', verbose_name='Valor da vida do pokémon')),
                ('ataque', models.IntegerField(help_text='55', verbose_name='Valor de ataque do pokémon')),
                ('defesa', models.IntegerField(help_text='76', verbose_name='Valor de defes do pokémon')),
                ('ataque_especial', models.IntegerField(help_text='34', verbose_name='Valor do Sp.Atk (ataque especial) do pokémon')),
                ('defesa_especial', models.IntegerField(help_text='45', verbose_name='Valor do Sp.Def (defesa especial) do pokémon')),
                ('habilidade_1', models.CharField(error_messages={'required': 'Por favor, insira essa habilidade do pokémon.'}, help_text='Ex: Calda de ferro', max_length=50, verbose_name='Primeira habilidade')),
                ('habilidade_2', models.CharField(error_messages={'required': 'Por favor, insira essa habilidade do pokémon.'}, help_text='Ex: Chute duplo', max_length=50, verbose_name='Segunda habilidade')),
                ('habilidade_3', models.CharField(error_messages={'required': 'Por favor, insira essa habilidade do pokémon.'}, help_text='Ex: Endurecer', max_length=50, verbose_name='Terceira habilidade')),
                ('habilidade_4', models.CharField(error_messages={'required': 'Por favor, insira essa habilidade do pokémon.'}, help_text='Ex: Investida', max_length=50, verbose_name='Quarta habilidade')),
            ],
        ),
    ]
