# Generated by Django 4.0.3 on 2022-04-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropokemon',
            name='ataque',
            field=models.IntegerField(help_text='Ex: 55', verbose_name='Valor de ataque do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='ataque_especial',
            field=models.IntegerField(help_text='Ex: 34', verbose_name='Valor do Sp.Atk (ataque especial) do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa',
            field=models.IntegerField(help_text='Ex: 76', verbose_name='Valor de defes do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa_especial',
            field=models.IntegerField(help_text='Ex: 45', verbose_name='Valor do Sp.Def (defesa especial) do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='hp',
            field=models.IntegerField(help_text='Ex: 87', verbose_name='Valor da vida do pokémon'),
        ),
    ]
