# Generated by Django 4.0.3 on 2022-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_cadastropokemon_ataque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa',
            field=models.IntegerField(help_text='Ex: 76', verbose_name='Valor de defesa do pokémon'),
        ),
    ]
