# Generated by Django 4.0.3 on 2022-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_cadastropokemon_defesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropokemon',
            name='imagem_pokemon',
            field=models.ImageField(blank=True, upload_to='imagens/imagem_inteira', verbose_name='Imagem do pokémon inteiro'),
        ),
        migrations.AddField(
            model_name='cadastropokemon',
            name='pixel_pokemon',
            field=models.ImageField(blank=True, upload_to='imagens/pixel', verbose_name='Imagem do pokémon em pixel'),
        ),
    ]
