# Generated by Django 4.0.3 on 2022-04-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_cadastropokemon_imagem_pokemon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropokemon',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Marque a opção se quer que o pokémon seja exibido no site.', verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='cadastropokemon',
            name='velocidade',
            field=models.IntegerField(default=45, help_text='Ex: 75', verbose_name='Velocidade'),
            preserve_default=False,
        ),
    ]
