# Generated by Django 4.0.3 on 2022-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_cadastropokemon_publicado_cadastropokemon_velocidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropokemon',
            name='numero_pokedex',
            field=models.IntegerField(error_messages={'required': 'É necessário escolher o número da pokedex.'}, help_text='Ex: 1, 10, 100', verbose_name='Número da Pokédex'),
        ),
    ]
