# Generated by Django 4.0.3 on 2022-04-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_remove_cadastropokemon_imagem_pokemon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropokemon',
            name='total',
            field=models.IntegerField(default=300, editable=False, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='ataque',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 55', verbose_name='Valor de ataque do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='ataque_especial',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 34', verbose_name='Valor do Sp.Atk (ataque especial) do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 76', verbose_name='Valor de defesa do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa_especial',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 45', verbose_name='Valor do Sp.Def (defesa especial) do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='hp',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 87', verbose_name='Valor da vida do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='velocidade',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 75', verbose_name='Velocidade'),
        ),
    ]
