# Generated by Django 4.0.3 on 2022-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_alter_cadastropokemon_ataque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropokemon',
            name='ataque',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 55', verbose_name='Valor de ataque do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='ataque_especial',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 34', verbose_name='Valor do Sp.Atk (ataque especial) do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 76', verbose_name='Valor de defesa do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='defesa_especial',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 45', verbose_name='Valor do Sp.Def (defesa especial) do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='hp',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 87', verbose_name='Valor da vida do pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='nome',
            field=models.CharField(default='Missigno', editable=False, error_messages={'required': 'Por favor, insira o nome do Pokémon.'}, help_text='Ex: Blaziken', max_length=100, verbose_name='Nome do Pokémon'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='tipo_1',
            field=models.CharField(default='Normal', editable=False, error_messages={'required': 'É necessário escolher o primeiro tipo.'}, help_text='Escolha um tipo para o pokémon', max_length=50, verbose_name='Primeiro tipo'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='tipo_2',
            field=models.CharField(blank=True, editable=False, help_text='Escolha o segundo tipo para o pokémon, se necessário', max_length=50, null=True, verbose_name='Segundo tipo'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='total',
            field=models.IntegerField(default=300, editable=False, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cadastropokemon',
            name='velocidade',
            field=models.IntegerField(default=50, editable=False, help_text='Ex: 75', verbose_name='Velocidade'),
        ),
    ]
